version: 2.1
orbs:
  node: circleci/node@5

# Définition des jobs (tâches unitaires)
jobs:
  # JOB: Installation des dépendances
  install_dependencies:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Vérification de la version de Node.js
          command: node --version
      - persist_to_workspace:
          root: .
          paths:
            - .

  # JOB: Analyse de code
  code_analysis:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Exécution du linter
          command: echo "Vérification de la qualité du code"

  # JOB: Tests unitaires
  unit_tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - attach_workspace:
          at: .
      - run:
          command: npm install jest-junit
      - run:
          name: Exécution des tests unitaires
          command: npm run test:ci || echo "Tests non exécutés"
      - store_test_results:
          path: ./test-results/

# Workflows (orchestration des jobs)
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - install_dependencies
      - code_analysis:
          requires:
            - install_dependencies
      - unit_tests:
          requires:
            - install_dependencies