version: 2.1
orbs:
  node: circleci/node@5

jobs:
  #############################################
  # STAGE: BUILD (repris de votre config initiale)
  #############################################
  
  test-node:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      - run:
          name: Run tests
          command: npm run test:ci || echo "Skip tests"
      - store_test_results:
          path: ./test-results/
      - persist_to_workspace:
          root: .
          paths:
            - .
  
  #############################################
  # STAGE: TESTS (nouveaux jobs)
  #############################################
  
  integration-tests:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run integration tests
          command: echo "Running integration tests..."
  
  regression-tests:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run regression tests
          command: echo "Running regression tests..."
  
  performance-tests:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run performance tests
          command: echo "Running performance tests..."
  
  security-tests:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run security tests
          command: echo "Running security tests..."
  
  compatibility-tests:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run compatibility tests
          command: echo "Running browser compatibility tests..."
  
  accessibility-tests:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run accessibility tests
          command: echo "Running accessibility tests..."
  
  #############################################
  # STAGE: DEPLOY (nouveaux jobs)
  #############################################
  
  prepare-environment:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Prepare environment
          command: echo "Preparing deployment environment..."
  
  deploy_to_vercel:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Vercel CLI
          command: npm install -g vercel
      - run:
          name: Deploy to Vercel
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              vercel --prod --token ${VERCEL_TOKEN	} --yes
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              vercel --token ${VERCEL_TOKEN	} --yes
            fi
  
  verification-tests:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Verify deployment
          command: echo "Running post-deployment verification tests..."
  
  functional-validation:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Functional validation
          command: echo "Validating functionality in deployed environment..."
  
  load-tests:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Load testing
          command: echo "Running load tests on deployed application..."
  
  monitoring-setup:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Setup monitoring
          command: echo "Setting up monitoring and alerts..."

workflows:
  version: 2
  build-and-test:
    jobs:
      # STAGE: BUILD
      - test-node
      
      # STAGE: TESTS
      - integration-tests:
          requires:
            - test-node
      - regression-tests:
          requires:
            - test-node
      - performance-tests:
          requires:
            - integration-tests
      - security-tests:
          requires:
            - integration-tests
      - compatibility-tests:
          requires:
            - integration-tests
      - accessibility-tests:
          requires:
            - integration-tests
      
      # STAGE: DEPLOY
      - prepare-environment:
          requires:
            - regression-tests
            - performance-tests
            - security-tests
            - compatibility-tests
            - accessibility-tests
          filters:
            branches:
              only:
                - develop
                - integration
                - main
      - deploy_to_vercel:
          requires:
            - test-node
          filters:
            branches:
              only:
                - develop
                - main
      - verification-tests:
          requires:
            - deploy_to_vercel
          filters:
            branches:
              only:
                - develop
                - integration
                - main
      - functional-validation:
          requires:
            - verification-tests
          filters:
            branches:
              only:
                - develop
                - integration
                - main
      - load-tests:
          requires:
            - verification-tests
          filters:
            branches:
              only:
                - integration
                - main
      - monitoring-setup:
          requires:
            - functional-validation
          filters:
            branches:
              only:
                - develop
                - integration
                - main